backend:
  name: git-gateway
  branch: "gt-graph"            # The branch where content will be committed
  squash_merges: true

media_folder: "static/uploads"  # Where uploaded files go in the repo
public_folder: "/uploads"

collections:
  - name: "event"
    label: "Events"
    folder: "content/event"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "publication"
    label: "Publications"
    folder: "content/publication"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Abstract", name: "abstract", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }
