name: Build & Deploy Hugo with Diagnostics

on:
  push:
    branches: ["gh-pages"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout source code
      - uses: actions/checkout@v4

      # 2️⃣ Setup Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.119.0'
          extended: true

      # 3️⃣ Print environment variables (for diagnostics)
      - name: Show environment variables
        run: env

      # 4️⃣ Clean Hugo cache and modules
      - name: Clean Hugo cache and modules
        run: |
          hugo mod clean
          hugo mod tidy
          rm -rf public resources

      # 5️⃣ Dry run build (diagnostic)
      - name: Hugo build (verbose)
        run: hugo --minify --baseURL "https://isa-group.github.io/aseproject/" --verbose

      # 6️⃣ List generated files (diagnostic)
      - name: List generated files
        run: ls -R public || echo "No public folder yet"

      # 7️⃣ Upload artifact for inspection (optional)
      - name: Upload public folder for inspection
        uses: actions/upload-artifact@v4
        with:
          name: hugo-public
          path: ./public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
